Show friendly error when plugin is missing
If you try to run a task but the namespace of the task is not
recognized, tomo will now helpfully suggest that you may need to load
the plugin that defines that namespace. E.g.

```
$ tomo run sidekiq:setup
tomo run v0.12.0

  ERROR: sidekiq:setup is not a recognized task.
  To see a list of all available tasks, run tomo tasks.

  Did you forget to install the sidekiq plugin?
```