Fix 'Could not guess bundler version' error with Bundler 4 (#519)
Bundler 4 changes the format of `Gemfile.lock` slightly: it now uses 2
spaces instead of 3 spaces for indentation of the `BUNDLER VERSION`
value.

This fixes the following error when parsing a Bundler 4 lock file:

```
ERROR: The bundler:upgrade_bundler task failed on deployer@localhost:55000.

Could not guess bundler version from Gemfile.lock.
Use the :bundler_version setting to specify the version of bundler to install.
```